name: Compile and Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node 12
      uses: actions/setup-node@v1
      
    - name: Compile Typescript
      run: |
        npm ci
        npm run tsc

    - name: Run Tests
      run: |
        npm test
